live_config_reload = true

[window]
dimensions = { columns = 140, lines = 40 }

[font]
normal = { family = "FantasqueSansM Nerd Font", style = "Regular" }
size = 16

[colors]
[colors.primary]
background = "#282828"
foreground = "#dfbf8e"

[colors.normal]
black = "#665c54"
red = "#ea6962"
green = "#a9b665"
yellow = "#e78a4e"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#dfbf8e"

[colors.bright]
black = "#928374"
red = "#ea6962"
green = "#a9b665"
yellow = "#e3a84e"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#dfbf8e"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001BF"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001BB"
