ZSH_DISABLE_COMPFIX=true
export PATH=$HOME/brew/bin:$HOME/bin:/usr/local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="mh"
DISABLE_UNTRACKED_FILES_DIRTY="true"
plugins=(git)
source $ZSH/oh-my-zsh.sh
fpath=(/usr/local/share/zsh-completions $fpath)
alias ll='lsd -lh'
alias ls='lsd'
alias tree='ls --tree'
alias gl='git log --graph --decorate --pretty=oneline --abbrev-commit'
alias gs='git status --renames'
export PATH=$PATH:$HOME/bin